my_dict = {'id: 14891':
         {'cdek_id': 435,
          'name': 'Краснодар',

          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'krasnodar',
          'fullname': 'Краснодар, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14892':
         {'cdek_id': 261,
          'name': 'Оренбург',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'orenburg',
          'fullname': 'Оренбург, Оренбургская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14893':
         {'cdek_id': 614,
          'name': 'Заречный, Свердловская обл.',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'zarechnyj-sverdlovskaa-obl',
          'fullname': 'Заречный, Свердловская обл., Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14894':
         {'cdek_id': 699,
          'name': 'Курск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kursk',
          'fullname': 'Курск, Курская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14895':
         {'cdek_id': 44,
          'name': 'Москва',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'moscow',
          'fullname': 'Москва, Москва, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14896':
         {'cdek_id': 1545,
          'name': 'Нахабино',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'nakhabino',
          'fullname': 'Нахабино, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14897':
         {'cdek_id': 137,
          'name': 'Санкт-Петербург',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'saint-petersburg',
          'fullname': 'Санкт-Петербург, Санкт-Петербург, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14898':
         {'cdek_id': 259,
          'name': 'Челябинск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'chelyabinsk',
          'fullname': 'Челябинск, Челябинская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14899':
         {'cdek_id': 165,
          'name': 'Кострома',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kostroma',
          'fullname': 'Кострома, Костромская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14900':
         {'cdek_id': 520,
          'name': 'Одинцово',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'odintsovo',
          'fullname': 'Одинцово, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14901':
         {'cdek_id': 270,
          'name': 'Новосибирск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'novosibirsk',
          'fullname': 'Новосибирск, Новосибирская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14902':
         {'cdek_id': 268,
          'name': 'Омск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'omsk',
          'fullname': 'Омск, Омская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14903':
         {'cdek_id': 1085,
          'name': 'Черкесск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'cherkessk',
          'fullname': 'Черкесск, Карачаево-Черкесская респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14904':
         {'cdek_id': 506,
          'name': 'Воронеж',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'voronezh',
          'fullname': 'Воронеж, Воронежская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14905':
         {'cdek_id': 256,
          'name': 'Уфа',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'ufa',
          'fullname': 'Уфа, Башкортостан респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14906':
         {'cdek_id': 250,
          'name': 'Екатеринбург',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'yekaterinburg',
          'fullname': 'Екатеринбург, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14907':
         {'cdek_id': 443,
          'name': 'Назрань',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'nazran',
          'fullname': 'Назрань, Ингушетия респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14908':
         {'cdek_id': 78,
          'name': 'Тосно',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tosno',
          'fullname': 'Тосно, Ленинградская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14909':
         {'cdek_id': 1009,
          'name': 'Павлово',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'pavlovo',
          'fullname': 'Павлово, Нижегородская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14910':
         {'cdek_id': 439,
          'name': 'Ставрополь',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'stavropol',
          'fullname': 'Ставрополь, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14911':
         {'cdek_id': 1606,
          'name': 'Лабинск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'labinsk',
          'fullname': 'Лабинск, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14912':
         {'cdek_id': 1235,
          'name': 'Ессентуки',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'yessentuki',
          'fullname': 'Ессентуки, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14914':
         {'cdek_id': 2375,
          'name': 'Пограничный',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'pogranichnyj',
          'fullname': 'Пограничный, Приморский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14916':
         {'cdek_id': 424,
          'name': 'Казань',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kazan',
          'fullname': 'Казань, Татарстан респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14917':
         {'cdek_id': 1305,
          'name': 'Горелово',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'gorelovo',
          'fullname': 'Горелово, Санкт-Петербург, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14918':
         {'cdek_id': 278,
          'name': 'Красноярск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'krasnoyarsk',
          'fullname': 'Красноярск, Красноярский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14919':
         {'cdek_id': 415,
          'name': 'Киров',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kirov-kirovskaa-obl',
          'fullname': 'Киров, Кировская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14920':
         {'cdek_id': 15514,
          'name': 'Черноморское',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'chernomorskoye-ar-krym',
          'fullname': 'Черноморское, Крым респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14922':
         {'cdek_id': 1097,
          'name': 'Балашиха',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'balashikha',
          'fullname': 'Балашиха, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14923':
         {'cdek_id': 245,
          'name': 'Тверь',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tver',
          'fullname': 'Тверь, Тверская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14924':
         {'cdek_id': 1386,
          'name': 'Апшеронск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'apsheronsk',
          'fullname': 'Апшеронск, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14925':
         {'cdek_id': 273,
          'name': 'Новокузнецк',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'novokuznetsk',
          'fullname': 'Новокузнецк, Кемеровская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14927':
         {'cdek_id': 987,
          'name': 'Мончегорск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'monchegorsk',
          'fullname': 'Мончегорск, Мурманская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14928':
         {'cdek_id': 337,
          'name': 'Белгород',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'belgorod',
          'fullname': 'Белгород, Белгородская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14929':
         {'cdek_id': 150,
          'name': 'Тула',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tula',
          'fullname': 'Тула, Тульская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14930':
         {'cdek_id': 12,
          'name': 'Новый Уренгой',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'novy-urengoy',
          'fullname': 'Новый Уренгой, Ямало-Ненецкий авт. округ, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14931':
         {'cdek_id': 132,
          'name': 'Старый Оскол',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'stary-oskol',
          'fullname': 'Старый Оскол, Белгородская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14932':
         {'cdek_id': 628,
          'name': 'Туймазы',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tujmazy',
          'fullname': 'Туймазы, Башкортостан респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14934':
         {'cdek_id': 412,
          'name': 'Чехов',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'chekhov',
          'fullname': 'Чехов, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14935':
         {'cdek_id': 534,
          'name': 'Монино',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'monino',
          'fullname': 'Монино, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14936':
         {'cdek_id': 540,
          'name': 'Урай',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'uraj',
          'fullname': 'Урай, Ханты-Мансийский авт. округ, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14937':
         {'cdek_id': 164,
          'name': 'Иваново',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'ivanovo',
          'fullname': 'Иваново, Ивановская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14938':
         {'cdek_id': 199,
          'name': 'Минеральные Воды',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'mineralnye-vody',
          'fullname': 'Минеральные Воды, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14939':
         {'cdek_id': 961,
          'name': 'Копейск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kopejsk',
          'fullname': 'Копейск, Челябинская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14941':
         {'cdek_id': 357,
          'name': 'Лиски, Лискинский р-н',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'liski',
          'fullname': 'Лиски, Лискинский р-н, Воронежская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14942':
         {'cdek_id': 248,
          'name': 'Пермь',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'perm',
          'fullname': 'Пермь, Пермский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14943':
         {'cdek_id': 1233,
          'name': 'Майкоп',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'maykop',
          'fullname': 'Майкоп, Адыгея респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14944':
         {'cdek_id': 419,
          'name': 'Чебоксары',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'cheboksary',
          'fullname': 'Чебоксары, Чувашия респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14945':
         {'cdek_id': 1250,
          'name': 'Томилино',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tomilino',
          'fullname': 'Томилино, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14946':
         {'cdek_id': 1002,
          'name': 'Арзамас',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'arzamas',
          'fullname': 'Арзамас, Нижегородская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14947':
         {'cdek_id': 252,
          'name': 'Тюмень',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tyumen',
          'fullname': 'Тюмень, Тюменская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14948':
         {'cdek_id': 62,
          'name': 'Кисловодск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kislovodsk',
          'fullname': 'Кисловодск, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14949':
         {'cdek_id': 17,
          'name': 'Пушкино',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'pushkino',
          'fullname': 'Пушкино, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14950':
         {'cdek_id': 274,
          'name': 'Барнаул',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'barnaul',
          'fullname': 'Барнаул, Алтайский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14951':
         {'cdek_id': 981,
          'name': 'Гатчина',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'gatchina',
          'fullname': 'Гатчина, Ленинградская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14952':
         {'cdek_id': 631,
          'name': 'Белебей',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'belebej',
          'fullname': 'Белебей, Башкортостан респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14953':
         {'cdek_id': 1299,
          'name': 'Жуковский',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'zhukovskij',
          'fullname': 'Жуковский, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14954':
         {'cdek_id': 450,
          'name': 'Петрозаводск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'petrozavodsk',
          'fullname': 'Петрозаводск, Карелия респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14955':
         {'cdek_id': 438,
          'name': 'Ростов-на-Дону',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'rostov-on-don',
          'fullname': 'Ростов-на-Дону, Ростовская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14956':
         {'cdek_id': 414,
          'name': 'Нижний Новгород',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'nizhny-novgorod',
          'fullname': 'Нижний Новгород, Нижегородская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14957':
         {'cdek_id': 2105,
          'name': 'Щекино',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'schekino',
          'fullname': 'Щекино, Тульская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14958':
         {'cdek_id': 3015,
          'name': 'Иноземцево',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'inozemtsevo',
          'fullname': 'Иноземцево, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14959':
         {'cdek_id': 1604,
          'name': 'Курганинск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kurganinsk',
          'fullname': 'Курганинск, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14960':
         {'cdek_id': 388,
          'name': 'Вятские Поляны',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'vyatskie-polyany',
          'fullname': 'Вятские Поляны, Кировская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14961':
         {'cdek_id': 432,
          'name': 'Астрахань',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'astrakhan',
          'fullname': 'Астрахань, Астраханская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14962':
         {'cdek_id': 1099,
          'name': 'Бронницы',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'bronnitsy',
          'fullname': 'Бронницы, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14963':
         {'cdek_id': 1069,
          'name': 'Таганрог',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'taganrog',
          'fullname': 'Таганрог, Ростовская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14964':
         {'cdek_id': 431,
          'name': 'Тольятти',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tolyatti',
          'fullname': 'Тольятти, Самарская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14965':
         {'cdek_id': 437,
          'name': 'Сочи',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'sochi',
          'fullname': 'Сочи, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14966':
         {'cdek_id': 1567,
          'name': 'Софрино, Пушкинский р-н',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'sofrino',
          'fullname': 'Софрино, Пушкинский р-н, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14967':
         {'cdek_id': 1756,
          'name': 'Котлас',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kotlas',
          'fullname': 'Котлас, Архангельская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14968':
         {'cdek_id': 53,
          'name': 'Артем',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'artem',
          'fullname': 'Артем, Приморский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14969':
         {'cdek_id': 1121,
          'name': 'Климовск мкр, Подольск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'klimovsk',
          'fullname': 'Климовск мкр, Подольск, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14970':
         {'cdek_id': 1482,
          'name': 'Новоалександровск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'novoaleksandrovsk',
          'fullname': 'Новоалександровск, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14971':
         {'cdek_id': 903,
          'name': 'Комсомольск-на-Амуре',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'komsomolsk-on-amur',
          'fullname': 'Комсомольск-на-Амуре, Хабаровский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14972':
         {'cdek_id': 152,
          'name': 'Калининград',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'kaliningrad',
          'fullname': 'Калининград, Калининградская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14973':
         {'cdek_id': 151,
          'name': 'Пятигорск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'pyatigorsk',
          'fullname': 'Пятигорск, Ставропольский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14975':
         {'cdek_id': 491,
          'name': 'Сарапул',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'sarapul',
          'fullname': 'Сарапул, Удмуртия респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14976':
         {'cdek_id': 521,
          'name': 'Красногорск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'krasnogorsk',
          'fullname': 'Красногорск, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14977':
         {'cdek_id': 486,
          'name': 'Можайск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'mozhajsk',
          'fullname': 'Можайск, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14978':
         {'cdek_id': 320,
          'name': 'Липецк',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'lipetsk',
          'fullname': 'Липецк, Липецкая обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14979':
         {'cdek_id': 601,
          'name': 'Серов',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'serov',
          'fullname': 'Серов, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14980':
         {'cdek_id': 428,
          'name': 'Саратов',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'saratov',
          'fullname': 'Саратов, Саратовская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14982':
         {'cdek_id': 1267,
          'name': 'Ирбит',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'irbit',
          'fullname': 'Ирбит, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14983':
         {'cdek_id': 616,
          'name': 'Первоуральск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'pervouralsk',
          'fullname': 'Первоуральск, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14985':
         {'cdek_id': 580,
          'name': 'Чернушка',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'chernushka',
          'fullname': 'Чернушка, Пермский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14986':
         {'cdek_id': 94,
          'name': 'Владимир',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'vladimir',
          'fullname': 'Владимир, Владимирская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14987':
         {'cdek_id': 13,
          'name': 'Белореченск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'belorechensk',
          'fullname': 'Белореченск, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14988':
         {'cdek_id': 283,
          'name': 'Якутск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'yakutsk',
          'fullname': 'Якутск, Саха респ. (Якутия), Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14989':
         {'cdek_id': 426,
          'name': 'Волгоград',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'volgograd',
          'fullname': 'Волгоград, Волгоградская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14990':
         {'cdek_id': 1339,
          'name': 'Нижняя Тура',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'nizhnyaya-tura',
          'fullname': 'Нижняя Тура, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14992':
         {'cdek_id': 146,
          'name': 'Ярославль',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'yaroslavl',
          'fullname': 'Ярославль, Ярославская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14993':
         {'cdek_id': 157,
          'name': 'Подольск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'podolsk',
          'fullname': 'Подольск, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14994':
         {
          'cdek_id': 269,
          'name': 'Томск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'tomsk',
          'fullname': 'Томск, Томская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14995':
         {
          'cdek_id': 1618,
          'name': 'Северская',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'severskaya',
          'fullname': 'Северская, Краснодарский край, Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14997':
         {
          'cdek_id': 611,
          'name': 'Новоуральск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'novouralsk',
          'fullname': 'Новоуральск, Свердловская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14998':
         {
          'cdek_id': 479,
          'name': 'Солнечногорск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'solnechnogorsk',
          'fullname': 'Солнечногорск, Московская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 14999':
         {
          'cdek_id': 561,
          'name': 'Глазов',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'glazov',
          'fullname': 'Глазов, Удмуртия респ., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 15000':
         {
          'cdek_id': 422,
          'name': 'Ульяновск',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'ulyanovsk',
          'fullname': 'Ульяновск, Ульяновская обл., Россия',
          '__typename': 'WebsiteEntityCity'},
        'id: 15001':
         {
          'cdek_id': 1315,
          'name': 'Великие Луки',
          'locale': 'ru',
          'country_code': 'ru',
          'country': 'Россия',
          'url': 'velikie-luki',
          'fullname': 'Великие Луки, Псковская обл., Россия',
          '__typename': 'WebsiteEntityCity'}
        }
