# Generated by Django 3.1 on 2020-10-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=50)),
                ('color_sort', models.IntegerField()),
                ('color_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=60)),
                ('product_vendor_code', models.CharField(max_length=10, unique=True)),
                ('product_img', models.CharField(max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_content', models.TextField()),
                ('product_url', models.CharField(max_length=50, unique=True)),
                ('product_file', models.CharField(blank=True, max_length=100, null=True)),
                ('product_price', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_sort', models.IntegerField()),
                ('category_url', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_title', models.CharField(max_length=10)),
                ('volume_sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductVolumePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeprice_price', models.CharField(max_length=10)),
                ('volumeprice_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
                ('volumeprice_volume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.volume')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_title', models.CharField(max_length=200)),
                ('attribute_sort', models.IntegerField()),
                ('attribute_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.productcategory'),
        ),
        migrations.AddField(
            model_name='color',
            name='color_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.colorgroup'),
        ),
    ]
