# Generated by Django 3.1 on 2021-02-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_url',
            field=models.SlugField(unique=True, verbose_name='Ссылка url'),
        ),
    ]
