# Generated by Django 3.1 on 2021-02-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210202_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttab',
            options={'ordering': ['-id'], 'verbose_name': 'Вкладка', 'verbose_name_plural': 'Вкладки'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись'),
        ),
    ]
