# Generated by Django 3.1 on 2020-10-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20201012_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_parent',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.productcategory'),
        ),
    ]
