# Generated by Django 3.1 on 2021-02-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20210203_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttab',
            name='tab_sort',
            field=models.IntegerField(default='0', verbose_name='Сортировка'),
        ),
    ]
