# Generated by Django 3.1 on 2020-10-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20201012_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['category_parent__id', 'category_sort']},
        ),
    ]
