# Generated by Django 3.1 on 2021-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_producttab_tab_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_description',
            field=models.TextField(blank=True, help_text='Отображается на странице категории, перед списком товаров', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
