# Generated by Django 3.1 on 2020-10-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20201012_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_title', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('root_url', models.SlugField(unique=True, verbose_name='Ссылка url')),
                ('vendor_img', models.ImageField(blank=True, upload_to='vendors', verbose_name='Изображение')),
                ('vendor_show', models.BooleanField(default=True, verbose_name='Показывать?')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_show',
            field=models.BooleanField(default=True, verbose_name='Показывать?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Product.productcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_count',
            field=models.CharField(blank=True, default='В наличии более 10л.', max_length=30, null=True, verbose_name='Наличие товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительное описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to='product/files', verbose_name='Прикрепить файл (Техническое руководство) pdf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f3219cf81c0>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Ссылка url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vendor_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.productvendor', verbose_name='Поставщик'),
        ),
    ]
