# Generated by Django 3.1 on 2021-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_productcategory_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_description',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_description_after',
            field=models.TextField(blank=True, help_text='Отображается на странице категории, ПОСЛЕ списка товаров', null=True, verbose_name='Дополнительная информация ПОСЛЕ'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_description_before',
            field=models.TextField(blank=True, help_text='Отображается на странице категории, ПЕРЕД списком товаров', null=True, verbose_name='Дополнительная информация ДО'),
        ),
    ]
