# Generated by Django 3.1 on 2020-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20201016_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_sort', 'color_title'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(blank=True, to='Product.Color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_image',
            field=models.ImageField(upload_to='colors', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_title',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f2db2cf32e0>/', verbose_name='Изображение товара'),
        ),
    ]
