# Generated by Django 3.1 on 2020-10-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20201016_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['attribute_sort', 'attribute_title'], 'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='productvolumeprice',
            options={'ordering': ['volumeprice_sort', 'volumeprice_volume'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['volume_sort', 'volume_title'], 'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_title',
            field=models.CharField(blank=True, default='Объем', max_length=30, null=True, verbose_name='Название опции для нескольких цен'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Значение атрибута (необязательно)'),
        ),
        migrations.AddField(
            model_name='productvolumeprice',
            name='volumeprice_sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(blank=True, to='Product.ColorGroup', verbose_name='Группа цветов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f98005215e0>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Цена (если пусто, то цена берется из таблицы ниже)'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_title',
            field=models.CharField(max_length=200, verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_price',
            field=models.CharField(max_length=10, verbose_name='Цены'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.volume', verbose_name='Опции'),
        ),
    ]
