# Generated by Django 3.1 on 2020-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20201016_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorgroup',
            options={'verbose_name': 'Цвета (группа)', 'verbose_name_plural': 'Цвета (группы)'},
        ),
        migrations.AlterModelOptions(
            name='productvendor',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7fcf6863a760>/', verbose_name='Изображение товара'),
        ),
    ]
