# Generated by Django 3.1 on 2020-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20201016_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f5f3ab2e760>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Атрибут'),
        ),
    ]
