# Generated by Django 3.1 on 2020-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20201016_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7fb35fbb6700>/', verbose_name='Изображение товара'),
        ),
    ]
