# Generated by Django 3.1 on 2020-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_auto_20201017_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvolumeprice',
            name='volumeprice_expenditure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='productvolumeprice',
            name='volumeprice_expenditure_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена за м2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f752fcb7b80>/', verbose_name='Изображение товара'),
        ),
    ]
