# Generated by Django 3.1 on 2020-10-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20201017_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price_title',
            new_name='product_price_title_1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_title_2',
            field=models.CharField(blank=True, default='Цена', max_length=30, null=True, verbose_name='Название опции для нескольких цен'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_title_3',
            field=models.CharField(blank=True, default='Расход', max_length=30, null=True, verbose_name='Название опции для нескольких цен'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_title_4',
            field=models.CharField(blank=True, default='Цена за м2', max_length=30, null=True, verbose_name='Название опции для нескольких цен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7fbe8fd4fb80>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_expenditure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Столбец 3'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_expenditure_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Столбец 4'),
        ),
        migrations.AlterField(
            model_name='productvolumeprice',
            name='volumeprice_price',
            field=models.CharField(max_length=10, verbose_name='Столбец 2'),
        ),
    ]
