# Generated by Django 3.1 on 2020-10-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20201017_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f9303ad5b80>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_1',
            field=models.CharField(blank=True, default='Объем', max_length=30, null=True, verbose_name='Ценник 1 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_2',
            field=models.CharField(blank=True, default='Цена', max_length=30, null=True, verbose_name='Ценник 2 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_3',
            field=models.CharField(blank=True, default='Расход', max_length=30, null=True, verbose_name='Ценник 3 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_4',
            field=models.CharField(blank=True, default='Цена за м2', max_length=30, null=True, verbose_name='Ценник 4 столбик'),
        ),
    ]
