# Generated by Django 3.1 on 2020-10-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_auto_20201017_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7f3ac36e4b80>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Простая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_choice',
            field=models.BooleanField(choices=[(True, 'Простая цена'), (False, 'Расширенная цена')], default=False, verbose_name='Тип цены'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_1',
            field=models.CharField(blank=True, default='Объем', max_length=50, null=True, verbose_name='Расширенная цена 1 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_2',
            field=models.CharField(blank=True, default='Цена', max_length=50, null=True, verbose_name='Расширенная цена 2 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_3',
            field=models.CharField(blank=True, default='Расход', max_length=50, null=True, verbose_name='Расширенная цена 3 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_title_4',
            field=models.CharField(blank=True, default='Цена за м2', max_length=50, null=True, verbose_name='Расширенная цена 4 столбик'),
        ),
    ]
