# Generated by Django 3.1 on 2020-10-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_auto_20201017_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttab',
            name='tab_slug',
            field=models.SlugField(default='', verbose_name='Ссылка href="# ..."'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/<django.db.models.query_utils.DeferredAttribute object at 0x7fa599f07e20>/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='tab_title',
            field=models.CharField(max_length=200, verbose_name='Название доп. вкладки'),
        ),
    ]
