# Generated by Django 3.1 on 2020-10-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_auto_20201017_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_image',
            field=models.ImageField(upload_to='products/colors', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_title',
            field=models.CharField(max_length=50, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='color_group_name',
            field=models.CharField(max_length=100, verbose_name='Группа цветов'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
