# Generated by Django 3.1 on 2020-10-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_auto_20201017_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_group', models.CharField(max_length=100, verbose_name='Дополнительные изображения')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to='products', verbose_name='Изображение товара')),
                ('img_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('img_alt', models.CharField(max_length=100, verbose_name='alt')),
                ('img_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.productimagegroup')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_imgs',
            field=models.ManyToManyField(blank=True, to='Product.ProductImage', verbose_name='Дополнительные изображения товара'),
        ),
    ]
