# Generated by Django 3.1 on 2020-10-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_auto_20201018_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['attribute_sort', 'id'], 'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_extra_desc',
            field=models.TextField(blank=True, help_text='Дополнительная информация, показывается рядом с ценой', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, help_text='Основное изображение товара, рекомендуемый размер 1000х700 px', null=True, upload_to='products', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_option_extra_1',
            field=models.CharField(blank=True, help_text='Расход&nbsp;на&nbsp;м&lt;sup&gt;2&lt;/sup&gt;&lt;br&gt;(1&nbsp;слой&nbsp;/&nbsp;2&nbsp;слоя)', max_length=50, null=True, verbose_name='Расширенная цена 3 столбик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_option_extra_2',
            field=models.CharField(blank=True, help_text='Цена&nbsp;р/м&lt;sup&gt;2&lt;/sup&gt;&lt;br&gt;(1&nbsp;слой&nbsp;/&nbsp;2&nbsp;слоя)', max_length=50, null=True, verbose_name='Расширенная цена 4 столбик'),
        ),
    ]
