# Generated by Django 3.1 on 2020-10-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0027_productvendor_vendor_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvendor',
            options={'ordering': ['vendor_sort'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_distinguish_bold',
            field=models.BooleanField(default=False, verbose_name='<b>'),
        ),
    ]
