# Generated by Django 3.1 on 2020-10-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_auto_20201023_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute_distinguish_empty',
            field=models.BooleanField(default=False, verbose_name='&nbsp;'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_distinguish_yellow',
            field=models.BooleanField(default=False, verbose_name='<yel>'),
        ),
    ]
