# Generated by Django 3.1 on 2020-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_auto_20201023_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_distinguish_colspan',
            field=models.BooleanField(default=False, help_text='Объединяет ячейки в одну', verbose_name='2:1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img_title',
            field=models.CharField(blank=True, help_text='Подпись под изображением и alt', max_length=100, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_distinguish_bold',
            field=models.BooleanField(default=False, help_text='Выделяет всю строку жирным', verbose_name='<b>'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_distinguish_empty',
            field=models.BooleanField(default=False, help_text='Включите, если хотите добавить пустую строку', verbose_name='nbsp'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_distinguish_yellow',
            field=models.BooleanField(default=False, help_text='Выделяет всю строку желтым фоном', verbose_name='bg-y'),
        ),
        migrations.AlterField(
            model_name='producttab',
            name='tab_slug',
            field=models.SlugField(default='additionally', verbose_name='Ссылка href="# ..."'),
        ),
    ]
