# Generated by Django 3.1 on 2020-10-24 19:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_auto_20201024_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_image',
            field=sorl.thumbnail.fields.ImageField(upload_to='products/colors', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Основное изображение товара, рекомендуемый размер 1000х700 px', null=True, upload_to='products', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img_file',
            field=sorl.thumbnail.fields.ImageField(upload_to='products', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productvendor',
            name='vendor_img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='vendors', verbose_name='Изображение'),
        ),
    ]
