# Generated by Django 3.1 on 2020-10-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_auto_20201024_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_group', models.CharField(max_length=100, verbose_name='Название группы опций')),
                ('option_type', models.CharField(choices=[('1', 'Radio Inputs'), ('2', 'Buttons')], default='1', max_length=50, verbose_name='Тип опций')),
                ('product_price_option', models.CharField(blank=True, default='Объем', max_length=50, null=True, verbose_name='Опция')),
                ('product_price_option_price', models.CharField(blank=True, default='Цена', max_length=50, null=True, verbose_name='Цена')),
                ('product_price_option_extra_1', models.CharField(blank=True, help_text='Расход&nbsp;на&nbsp;м&lt;sup&gt;2&lt;/sup&gt;&lt;br&gt;(1&nbsp;слой&nbsp;/&nbsp;2&nbsp;слоя)', max_length=50, null=True, verbose_name='Дополнительно 1')),
                ('product_price_option_extra_2', models.CharField(blank=True, help_text='Цена&nbsp;р/м&lt;sup&gt;2&lt;/sup&gt;&lt;br&gt;(1&nbsp;слой&nbsp;/&nbsp;2&nbsp;слоя)', max_length=50, null=True, verbose_name='Дополнительно 2')),
            ],
            options={
                'verbose_name': 'Группа опция',
                'verbose_name_plural': 'Группы опций',
            },
        ),
        migrations.CreateModel(
            name='OptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=10, verbose_name='Опция')),
                ('option_sort', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['option_sort', 'option_title'],
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_option_price', models.CharField(max_length=10, verbose_name='Цена')),
                ('product_option_extra_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дополнительно 1')),
                ('product_option_extra_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дополнительно 2')),
                ('product_option_sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.optiongroup', verbose_name='Группа опций')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.optionprice', verbose_name='Выберите опцию')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'ordering': ['product_option_sort', 'product_option'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_option',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_option_extra_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_option_extra_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price_option_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_choice',
            field=models.CharField(choices=[(True, 'Простая цена'), (False, 'Цена с опциями')], default=False, max_length=50, verbose_name='Тип цены'),
        ),
        migrations.DeleteModel(
            name='ProductVolumePrice',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_options',
            field=models.ManyToManyField(blank=True, to='Product.OptionGroup', verbose_name='Опции цены'),
        ),
    ]
