# Generated by Django 3.1 on 2020-10-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_auto_20201027_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optiongroup',
            options={'verbose_name': 'Опция (группа)', 'verbose_name_plural': 'Опции (группы)'},
        ),
        migrations.AlterModelOptions(
            name='productimagegroup',
            options={'verbose_name': 'Изображение (группа)', 'verbose_name_plural': 'Изображения (группы)'},
        ),
        migrations.AlterField(
            model_name='optiongroup',
            name='option_group',
            field=models.CharField(help_text='Например, название товара, к которому эти опции относятся', max_length=100, verbose_name='Название группы опций'),
        ),
    ]
