# Generated by Django 3.1 on 2020-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_auto_20201027_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptionprice',
            old_name='product',
            new_name='product_option_group',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price_choice',
            field=models.CharField(choices=[('1', 'Простая цена'), ('2', 'Цена с опциями')], default='2', max_length=50, verbose_name='Тип цены'),
        ),
    ]
