# Generated by Django 3.1 on 2020-10-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_auto_20201027_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='option_title',
            field=models.CharField(default='', help_text='Отображается рядом с опциями на странице товара', max_length=100, verbose_name='Заголовок'),
        ),
    ]
