# Generated by Django 3.1 on 2020-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_optiongroup_option_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='option_title',
            field=models.CharField(blank=True, help_text='Отображается рядом с опциями на странице товара', max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
