# Generated by Django 3.1 on 2020-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0036_auto_20201027_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiongroup',
            name='product_price_option_extra_1',
            field=models.CharField(blank=True, help_text='Расход&nbsp;м&lt;sup&gt;2&lt;/sup&gt;&lt;br&gt;(1&nbsp;слой&nbsp;/&nbsp;2&nbsp;слоя)<br>', max_length=50, null=True, verbose_name='Дополнительно 1'),
        ),
        migrations.AlterField(
            model_name='optionprice',
            name='option_title',
            field=models.CharField(max_length=20, verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='productoptionprice',
            name='product_option_price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена'),
        ),
    ]
