# Generated by Django 3.1 on 2020-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0037_auto_20201029_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorgroup',
            name='color_group_title',
            field=models.CharField(blank=True, help_text='Показывается во всплывающем окне при выборе цвета', max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='color_group_name',
            field=models.CharField(help_text='Показывается только в админке', max_length=100, verbose_name='Группа цветов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default=0, help_text='Введите цену без копеек и без знака рубля', max_length=30, verbose_name='Простая цена (Руб.)'),
        ),
    ]
