# Generated by Django 3.1 on 2020-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0040_auto_20201030_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiongroup',
            name='options_sort',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
