# Generated by Django 3.1 on 2020-11-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0042_auto_20201101_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['category_title', 'category_parent__id', 'category_sort'], 'verbose_name': 'Категория (Краски и масла)', 'verbose_name_plural': 'Категории (Краски и масла)'},
        ),
    ]
