# Generated by Django 3.1 on 2020-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(upload_to='index/slide/', verbose_name='Изображение слайда')),
                ('slide_description', models.TextField(blank=True, null=True, verbose_name='Текст / Описание')),
                ('slide_link_name', models.CharField(blank=True, default='Перейти', max_length=100, null=True, verbose_name='Название кнопки')),
                ('slide_link_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('slide_order', models.IntegerField(default='0', verbose_name='Порядок')),
                ('slide_visible', models.BooleanField(default=True, verbose_name='Показывать?')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['slide_order', 'id'],
            },
        ),
    ]
