# Generated by Django 3.1 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_link_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
