# Generated by Django 3.1 on 2020-10-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа слайдов',
                'verbose_name_plural': 'Группы слайдов',
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='slide_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='index.group'),
            preserve_default=False,
        ),
    ]
