# Generated by Django 3.1 on 2020-11-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20201112_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_link_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка'),
        ),
    ]
