# Generated by Django 3.1 on 2020-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201008_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_link_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
