# Generated by Django 3.1 on 2020-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20201008_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['slide_group', 'slide_order', 'id'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст / Описание (h2 / p)'),
        ),
    ]
