# Generated by Django 3.1 on 2020-10-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20201008_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа слайдов', 'verbose_name_plural': 'Группы слайдов'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
