# Generated by Django 3.1 on 2020-11-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_order'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_order'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='city',
            name='city_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_order',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
