# Generated by Django 3.1 on 2020-11-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Cart', '0002_auto_20201111_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_API', models.IntegerField(unique=True, verbose_name='API номер')),
                ('delivery_title', models.CharField(max_length=100, verbose_name='Название')),
                ('delivery_description', models.TextField(verbose_name='Описание')),
                ('delivery_img', models.ImageField(upload_to='delivery', verbose_name='Изображение')),
                ('delivery_enable', models.BooleanField(default=True, verbose_name='Включить')),
                ('delivery_city', models.ManyToManyField(to='Cart.City', verbose_name='Города для доставки')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255, verbose_name='ID')),
                ('item_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('item_options', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опции')),
                ('item_price', models.IntegerField(default=0, verbose_name='Цена')),
                ('item_count', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('item_sale', models.IntegerField(default=0, verbose_name='Скидка %')),
                ('item_sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('item_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.product', verbose_name='Товар из БД')),
            ],
            options={
                'verbose_name': 'Заказанный товар',
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, verbose_name='Статус')),
                ('status_order', models.IntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'ordering': ['status_order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_API', models.IntegerField(unique=True, verbose_name='API номер')),
                ('payment_title', models.CharField(max_length=100, verbose_name='Название')),
                ('payment_description', models.TextField(verbose_name='Описание')),
                ('payment_enable', models.BooleanField(default=True, verbose_name='Включить')),
                ('payment_delivery', models.ManyToManyField(to='Cart.Delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('order_history', models.TextField(verbose_name='История заказа')),
                ('order_comment', models.TextField(verbose_name='Комментарий от клиента')),
                ('order_comment_admin', models.TextField(help_text='Клиент этого не видит', verbose_name='Комментарий администратора')),
                ('order_country_city_index', models.CharField(max_length=255, verbose_name='Страна, город, индекс')),
                ('order_address', models.CharField(max_length=255, verbose_name='Улица, дом, квартира')),
                ('order_client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('order_phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('order_notification', models.BooleanField(verbose_name='Уведомлять по email?')),
                ('order_email', models.EmailField(max_length=254, verbose_name='Email для уведомлений')),
                ('order_call_me', models.BooleanField(verbose_name='Позвонить для подтверждения?')),
                ('order_delivery', models.ManyToManyField(to='Cart.Delivery', verbose_name='Доставка')),
                ('order_items', models.ManyToManyField(to='Cart.Item', verbose_name='Товары')),
                ('order_payment', models.ManyToManyField(to='Cart.Payment', verbose_name='Оплата')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cart.status', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
