# Generated by Django 3.1 on 2020-11-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_delivery_item_order_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Варианты оплаты'},
        ),
    ]
