# Generated by Django 3.1 on 2020-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_auto_20201112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
