# Generated by Django 3.1 on 2020-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20201112_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_delivery',
            field=models.ManyToManyField(blank=True, to='Cart.Delivery', verbose_name='Доставка'),
        ),
    ]
