# Generated by Django 3.1 on 2020-11-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_auto_20201112_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица, дом, квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_call_me',
            field=models.BooleanField(default=1, verbose_name='Позвонить для подтверждения?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий от клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_comment_admin',
            field=models.TextField(blank=True, help_text='Клиент этого не видит', null=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_country_city_index',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна, город, индекс'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Cart.delivery', verbose_name='Доставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_history',
            field=models.TextField(blank=True, null=True, verbose_name='История заказа'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Cart.payment', verbose_name='Оплата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
