# Generated by Django 3.1 on 2020-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_auto_20201113_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_default',
            field=models.BooleanField(default=0, verbose_name='По умолчанию'),
        ),
    ]
