# Generated by Django 3.1 on 2020-11-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0015_auto_20201113_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_pickup',
            field=models.BooleanField(default=0, verbose_name='Самовывоз'),
        ),
    ]
