# Generated by Django 3.1 on 2020-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0016_delivery_delivery_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_city',
            field=models.ManyToManyField(blank=True, null=True, to='Cart.City', verbose_name='Города для доставки'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_img',
            field=models.ImageField(blank=True, null=True, upload_to='delivery', verbose_name='Изображение'),
        ),
    ]
