# Generated by Django 3.1 on 2020-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0017_auto_20201113_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'ЗАКАЗ', 'verbose_name_plural': 'ЗАКАЗЫ'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_sum',
            field=models.IntegerField(default=0, verbose_name='Сумма заказа'),
        ),
    ]
