# Generated by Django 3.1 on 2021-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0018_auto_20201114_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_city',
            field=models.ManyToManyField(blank=True, to='Cart.City', verbose_name='Города для доставки'),
        ),
    ]
